### ISSUE TITLE
Teaching event on a VLCB Arduino board does not work.

### ISSUE THREAD

**Issue by SvenRosvall** [david284/MMC-SERVER#16]
Node->Stored Events panel: Press "Add Event". Short event with device number 222.
Afterwards the list of events is empty. 

Below is the debug output on the terminal window.
```
jsonServer: Data Received : {"mnemonic":"NNLRN","nodeNumber":256}{"mnemonic":"EVLRN","nodeNumber":0,"eventNumber":222,"eventVariableIndex":1,"eventVariableValue":0}{"mnemonic":"NNULN","nodeNumber":256}{"mnemonic":"NNULN","nodeNumber":256}{"mnemonic":"NERD","nodeNumber":256}{"mnemonic":"RQEVN","nodeNumber":256}{"mnemonic":"NERD","nodeNumber":256}{"mnemonic":"RQEVN","nodeNumber":256}{"mnemonic":"NERD","nodeNumber":256}
jsonServer: broadcast : {"mnemonic":"NNLRN","nodeNumber":256}
jsonServer: broadcast : {"mnemonic":"EVLRN","nodeNumber":0,"eventNumber":222,"eventVariableIndex":1,"eventVariableValue":0}
jsonServer: broadcast : {"mnemonic":"NNULN","nodeNumber":256}
jsonServer: broadcast : {"mnemonic":"NNULN","nodeNumber":256}
jsonServer: broadcast : {"mnemonic":"NERD","nodeNumber":256}
jsonServer: broadcast : {"mnemonic":"RQEVN","nodeNumber":256}
jsonServer: broadcast : {"mnemonic":"NERD","nodeNumber":256}
jsonServer: broadcast : {"mnemonic":"RQEVN","nodeNumber":256}
jsonServer: broadcast : {"mnemonic":"NERD","nodeNumber":256}
COM10 -> Transmit : :SB780N530100; NNLRN Opcode 53
COM10 -> Transmit : :SB780ND2000000DE0100; EVLRN Opcode D2
COM10 -> Transmit : :SB780N540100; NNULN Opcode 54
COM10 -> Transmit : :SB780N540100; NNULN Opcode 54
COM10 -> Transmit : :SB780N570100; NERD Opcode 57
COM10 -> Transmit : :SB780N580100; RQEVN Opcode 58
COM10 -> Transmit : :SB780N570100; NERD Opcode 57
COM10 -> Transmit : :SB780N580100; RQEVN Opcode 58
COM10 -> Transmit : :SB780N570100; NERD Opcode 57
COM10 <- Receive : :SB020N590100; WRACK Opcode 59
COM10 <- Receive : :SB020NAF0100D20400; GRSP Opcode AF
mergAdminNode: WRACK Opcode 59 processed
mergAdminNode: GRSP Opcode AF processed
socketServer: CBUS - Op Code Unknown : undefined
```
The event list is populated properly when I press "Refresh Events"

**Comment by david284** [comment]
Can you replicate this issue & include the debug log from the /log directory?
I don't see any responses to the NERD - but the console output is limited (to stop it being overwhelming)

I'm also a little concerned about the last entry - Opcode unknown - mainly because it's really unhelpful to not display the actual op code! - that's something to fix right away

**Comment by SvenRosvall** [comment]
[debug.log](https://github.com/david284/MMC-SERVER/files/13853171/debug.log)

**Comment by david284** [comment]
Missing support for GRSP added

The title says teaching event does not work, but the comment suggests it did, but just wasn't displayed until refreshed

Is this a good summary?

Could it be it was just taking too long to update the display?
This was raised as issue #7 - so possible duplicate?

**Comment by SvenRosvall** [comment]
No, it is not a duplicate of #7 . I monitored bus traffic with FCU and could see that the flurry of messages had ended.

**Comment by david284** [comment]
Ok, think I know what's happening
Looking at the log, there is no response to the NERD request
I think it's because the server isn't waiting for the WRACK before sending more commands, and I suspect some of the following command are being ignored by the module

So, I've implement a mechanism to request a NERD after the WRACK is received for a specific node
Pretty sure it'll fix the issue, so I'll close this
