### ISSUE TITLE
Edit event name in Nodes -> Stored Events

### ISSUE THREAD

**Issue by SvenRosvall** [david284/MMC-SERVER#3]
Yes I know I can edit the event name in the main "Events" page. However this only works for events that have been seen on the bus.
I'd like to be able to edit event names in the page where I edit events that are stored in a node. Some arguments:

1. This is also the place where new events are added, so I'd like to give a new event a name as soon as it is created.
2. Consumed events that are stored here and not produced anywhere else can't easily be produced. Think of short events created in FCU via Software Node, or new consumed events created on the Stored Events page. Thus they won't show up in the Events page.
3. When I see events in the main Events page (captured events) I don't see enough details of the event. I don't see event variables (as this requires the information from the node) so it is difficult to know which event is which here.

**Comment by david284** [comment]
Just looking at the naming issue..

The main difference is that the ‘events’ page is a single component that shows events that have been received, with an identity of event node number & event number (I’ll carry on using ‘identity’ for this pairing..) – irrespective of which node produced them (as producing nodes can ‘spoof’ other event nodes in Ian’s universal code, and maybe others..)

So, in principal, more than one node can produce (and/or consume) the same event ‘identity’

So, if you name a ‘stored event’ on a node – you could easily end up with different names on different nodes (and the events page) for the same event
Maybe that’s the intent?

If as I suspect, that’s not the intent, and an event ‘identity’ needs to have the same ‘name’ across the system, then I suspect that’ll need a lookup table so that each instance of that event ‘identity’ picks up the same name
That sounds the most sensible option to me, but I suspect it’ll need some investigation, as the event lookup table needs to be shared across all UI components – I’m sure that’s possible, It’ll just take a bit of looking into

If the naming isn’t just dependant on the event ‘identity’ but also the event variables, as your last comment seems to suggest, then that adds a deeper level of complexity – but maybe I’m reading to much into that?

Regards
David


Sent from Mail for Windows

From: Sven Rosvall
Sent: 30 December 2023 11:01
To: david284/MMC-SERVER
Cc: Subscribed
Subject: [david284/MMC-SERVER] Edit event name in Nodes -> Stored Events(Issue #3)

Yes I know I can edit the event name in the main "Events" page. However this only works for events that have been seen on the bus.
I'd like to be able to edit event names in the page where I edit events that are stored in a node. Some arguments:
1. This is also the place where new events are added, so I'd like to give a new event a name as soon as it is created.
2. Consumed events that are stored here and not produced anywhere else can't easily be produced. Think of short events created in FCU via Software Node, or new consumed events created on the Stored Events page. Thus they won't show up in the Events page.
3. When I see events in the main Events page (captured events) I don't see enough details of the event. I don't see event variables (as this requires the information from the node) so it is difficult to know which event is which here.

**Comment by SvenRosvall** [comment]
Yes, you suspect correctly.The event name in the Stored Events list should be reflected across all pages. Not only the captured events page but also if the same event (produced or consumed) is used by another node.

Fully appreciate that this is not trivial to implement. But I this is a feature that I think will help usage a lot, so please don't close this issue.

**Comment by david284** [comment]
Ok, I think I know what's needed - it'll need to be persistent, so stored over shutdown's

**Comment by dpharris** [comment]
Similarly to JMRI, the event's name is internal to JMRI, since they are not stored on in any node.  Yes, the association between an event-id (NN:EN) and its name needs to be persisted.  I would say the event-variables do not change the naming.  The event-variables are specific to each node's use of that event-id.  Also, the philosophy of Producer-Consumer is that each event-id has a specific meaning/usage.  That can range from "button-x is pushed" to "Emergency" to "Night has fallen".  

Isn't the implementation simply a table of event-id:names, which is persisted?

**Comment by david284** [comment]
`__Isn't the implementation simply a table of event-id:names, which is persisted?__
`
Yes, but you overestimate my web programming ability - the web pages run using a 'state' collection of data which needs updating when it's changed, and then it needs writing to the server to write it to file so that its persisted over a shutdown

All these mechanisms exist, but most where created by Nigel, so I have to work through them to figure out what needs to be done - the reactive nature of the web pages is very good, but has some complex mechanisms behind it
