### ISSUE TITLE
Efficient creating of (short) events.

### ISSUE THREAD

**Issue by SvenRosvall** [david284/MMC-SERVER#30]
Greg Palmer suggested a workflow he uses today with FCU:
1. Create a number of short events in the "Software Node"
1. Drag each event to the node(s) that shall produce or consume them.

This separates the task or creating the events from configuring them. You don't have to switch between creating them (with names) and configuring them. Often you want to create all the events and review the list of events before configuring them.

Another use case is where events are imported, i.e. from a spreadsheet that contains all the wiring of a layout.

This may require a lot of work for MMC. 
MMC doesn't have a "software node" and it doesn't store events "offline".

I have no recommendation on how to do this in MMC. Introducing a dummy node (like "software node") is one option. 

This also raises the question about storing events locally as these events are not (yet) stored on any nodes.

**Comment by david284** [comment]
_This separates the task of creating the events from configuring them_

Well, that's effectively what we originally had - but the 'quirk' of universal not allowing you to do that meant I took your suggestion of going straight to configuration after 'teaching'

So, I'm, not convinced that would work for universal anyway

In principal, I don't agree with having a 'software node' - it's an artificial construct that in my opinion isn't needed, and just adds confusion
Other than the need to configure at least one variable (because of universal) - I think the current process is more transparent and no more effort
