### ISSUE TITLE
CANPAN LED configurations options disappear after selecting LED Action

### ISSUE THREAD

**Issue by swinguk** [david284/MMC-SERVER#54]
MMC-Server v0.7.16
Steps to reproduce:
From Events view, select an event, and click Teach
From Node drop down list on left hand side, select a CANPAN Node to teach to, the following appears:
![shot1](https://github.com/user-attachments/assets/5b011bcc-2167-47ce-906d-caefd1bd78a8)
Select LED Action, and set to On, or set to Flash
Result: "LED Action" and all "LED 1" to "LED 32" disappear from the screen
![shot2](https://github.com/user-attachments/assets/3e910dfb-55e9-47c5-aa61-c0df9ae410f7)
Note, if you then Close, which returns you to the Teach menu, and you select "Variables" on the Node you were trying to teach, the On / Flash option will still be selected, and "LED Action" and all "LED1" to "LED 32" are available again for selecting the LEDs to change for this event

**Comment by david284** [comment]
Thanks for that
It's because CANPAN uses EV's to decide on visibility of other EV's (the only module that does this as far as I am aware, all others use NV's)
It only affects the first edit on a new event - before you change an EV, the event doesn't exist on the module, so the event and all it's variables are temporary on initially creating a new event
When you set an event variable, it does an EVLRN for that variable, which creates that event on the module, and re-reads that single variable (avoiding the time delay in reading all the event variables, which was a previous complaint)
But that overrides the all the temporary variables for that event - so the other EV's are null as not having been read yet, hence the visibility logic fails, as it's dependant on other EV's
This will be an issue for any EV changed other than the one used for the visibility logic

Once you close the process, and re-enter the event variables dialog, it refreshes all the variables, so as you found,  it then works as expected

I'll have a think about how to tackle that

**Comment by SvenRosvall** [comment]
David, we also have visibilityLogic with EV's in CANMIO-OUT, CANMIO-SVO, CANACC5, CANACC8. They were developed at the same time and with same design ideas so they are quite similar.

**Comment by david284** [comment]
Yes, I'd forgotten those also use that logic on EV's - I expect they'll have the same issue

Anyway, I'm testing a solution for it - basically, if it's a 'new' event, then it'll read all the event variables, not just the single event variable written - just want to check timing on module responses to minimise any 'jumps' in the display

**Comment by david284** [comment]
Changes made
https://github.com/david284/MMC-SERVER/commit/2f5a32eddb04b3a4258e7333f0556242f4ed440a
